# Site settings
baseURL = "http://cytodata.org/"
languageCode = "en-us"
title = "CytoData Society"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

# Top menu
[menu]
  [[menu.main]]
    identifier = "symposiums"
    name = "Symposiums"
    url = "/symposiums"
    weight = 10

  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources"
    weight = 20

  [[menu.main]]
    identifier = "leadership"
    name = "Leadership"
    url = "/leadership"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 40

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 50
  
[[menu.top]]
    name = "CytoData Symposium 2021 will be hosted virtually by bit.bio, October 13-15, 2021. More information will be available soon."
    weight = 10
    url = "https://www.cytodata.org/symposiums/2021/"

# Site parameters
[params]

    # Meta
    description = "CytoData Society"
    author = "Shantanu Singh & Tom Nijhof"
    keywords = "biology, computer vision, machine learning, drug discovery, high-content imaging, microscopy, bioinformatics, computational biology"
    
    # Back-to-top button name
    bttButton = ""
