[build]
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.127.0"

[context.production]
  command = "hugo --baseURL http://cytodata.org/"

[context.deploy-preview]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"